--------------------------------------------------------------------------------
-- Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____
--  /   /\/   /
-- /___/  \  /    Vendor: Xilinx
-- \   \   \/     Version: L.57
--  \   \         Application: netgen
--  /   /         Filename: mult16.vhd
-- /___/   /\     Timestamp: Thu Feb  4 11:50:39 2010
-- \   \  /  \ 
--  \___\/\___\
--             
-- Command	: -intstyle ise -w -sim -ofmt vhdl ./tmp/_cg/mult16.ngc ./tmp/_cg/mult16.vhd 
-- Device	: 5vlx330tff1738-2
-- Input file	: ./tmp/_cg/mult16.ngc
-- Output file	: ./tmp/_cg/mult16.vhd
-- # of Entities	: 1
-- Design Name	: mult16
-- Xilinx	: /vol/cc/opt/Xilinx/11.1/ISE
--             
-- Purpose:    
--     This VHDL netlist is a verification model and uses simulation 
--     primitives which may not represent the true implementation of the 
--     device, however the netlist is functionally correct and should not 
--     be modified. This file cannot be synthesized and should only be used 
--     with supported simulation tools.
--             
-- Reference:  
--     Command Line Tools User Guide, Chapter 23
--     Synthesis and Simulation Design Guide, Chapter 6
--             
--------------------------------------------------------------------------------


-- synthesis translate_off
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
use UNISIM.VPKG.ALL;

entity mult16 is
  port (
    ce : in STD_LOGIC := 'X'; 
    clk : in STD_LOGIC := 'X'; 
    a : in STD_LOGIC_VECTOR ( 15 downto 0 ); 
    b : in STD_LOGIC_VECTOR ( 15 downto 0 ); 
    p : out STD_LOGIC_VECTOR ( 31 downto 0 ) 
  );
end mult16;

architecture STRUCTURE of mult16 is
  signal BU2_N1 : STD_LOGIC; 
  signal NLW_VCC_P_UNCONNECTED : STD_LOGIC; 
  signal NLW_GND_G_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PATTERNBDETECT_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PATTERNDETECT_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_OVERFLOW_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_UNDERFLOW_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYCASCIN_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYCASCOUT_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_MULTSIGNIN_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_MULTSIGNOUT_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_A_29_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_A_28_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_A_27_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_A_26_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_A_25_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_47_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_46_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_45_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_44_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_43_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_42_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_41_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_40_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_39_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_38_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_37_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_36_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_35_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_34_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_33_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_32_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_31_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_30_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_29_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_28_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_27_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_26_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_25_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_24_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_23_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_22_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_21_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_20_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_19_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_18_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_17_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_16_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_15_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_14_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_13_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_12_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_11_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_10_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_9_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_8_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_7_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_6_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_5_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_4_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_3_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_2_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_1_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_0_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_47_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_46_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_45_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_44_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_43_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_42_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_41_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_40_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_39_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_38_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_37_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_36_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_35_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_34_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_33_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_32_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_31_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_30_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_29_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_28_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_27_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_26_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_25_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_24_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_23_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_22_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_21_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_20_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_19_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_18_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_17_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_16_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_15_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_14_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_13_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_12_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_11_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_10_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_9_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_8_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_7_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_6_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_5_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_4_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_3_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_2_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_1_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_0_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_17_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_16_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_15_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_14_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_13_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_12_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_11_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_10_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_9_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_8_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_7_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_6_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_5_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_4_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_3_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_2_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_1_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_0_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_47_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_46_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_45_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_44_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_43_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_42_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_41_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_40_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_39_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_38_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_37_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_36_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_35_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_34_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_33_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_32_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_31_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_30_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_29_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_28_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_27_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_26_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_25_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_24_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_23_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_22_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_21_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_20_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_19_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_18_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_17_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_16_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_15_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_14_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_13_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_12_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_11_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_10_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_9_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_8_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_7_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_6_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_5_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_4_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_3_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_2_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_1_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_0_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_47_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_46_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_45_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_44_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_43_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_42_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_41_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_40_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_39_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_38_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_37_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_36_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_35_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_34_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_33_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_32_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_17_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_16_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_15_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_14_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_13_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_12_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_11_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_10_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_9_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_8_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_7_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_6_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_5_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_4_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_3_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_2_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_1_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_0_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_29_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_28_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_27_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_26_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_25_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_24_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_23_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_22_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_21_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_20_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_19_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_18_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_17_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_16_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_15_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_14_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_13_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_12_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_11_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_10_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_9_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_8_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_7_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_6_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_5_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_4_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_3_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_2_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_1_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_0_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_29_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_28_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_27_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_26_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_25_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_24_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_23_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_22_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_21_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_20_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_19_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_18_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_17_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_16_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_15_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_14_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_13_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_12_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_11_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_10_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_9_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_8_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_7_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_6_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_5_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_4_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_3_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_2_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_1_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_0_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYOUT_3_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYOUT_2_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYOUT_1_UNCONNECTED : STD_LOGIC; 
  signal NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYOUT_0_UNCONNECTED : STD_LOGIC; 
  signal a_2 : STD_LOGIC_VECTOR ( 15 downto 0 ); 
  signal b_3 : STD_LOGIC_VECTOR ( 15 downto 0 ); 
  signal p_4 : STD_LOGIC_VECTOR ( 31 downto 0 ); 
  signal BU2_zero_detect : STD_LOGIC_VECTOR ( 0 downto 0 ); 
begin
  a_2(15) <= a(15);
  a_2(14) <= a(14);
  a_2(13) <= a(13);
  a_2(12) <= a(12);
  a_2(11) <= a(11);
  a_2(10) <= a(10);
  a_2(9) <= a(9);
  a_2(8) <= a(8);
  a_2(7) <= a(7);
  a_2(6) <= a(6);
  a_2(5) <= a(5);
  a_2(4) <= a(4);
  a_2(3) <= a(3);
  a_2(2) <= a(2);
  a_2(1) <= a(1);
  a_2(0) <= a(0);
  b_3(15) <= b(15);
  b_3(14) <= b(14);
  b_3(13) <= b(13);
  b_3(12) <= b(12);
  b_3(11) <= b(11);
  b_3(10) <= b(10);
  b_3(9) <= b(9);
  b_3(8) <= b(8);
  b_3(7) <= b(7);
  b_3(6) <= b(6);
  b_3(5) <= b(5);
  b_3(4) <= b(4);
  b_3(3) <= b(3);
  b_3(2) <= b(2);
  b_3(1) <= b(1);
  b_3(0) <= b(0);
  p(31) <= p_4(31);
  p(30) <= p_4(30);
  p(29) <= p_4(29);
  p(28) <= p_4(28);
  p(27) <= p_4(27);
  p(26) <= p_4(26);
  p(25) <= p_4(25);
  p(24) <= p_4(24);
  p(23) <= p_4(23);
  p(22) <= p_4(22);
  p(21) <= p_4(21);
  p(20) <= p_4(20);
  p(19) <= p_4(19);
  p(18) <= p_4(18);
  p(17) <= p_4(17);
  p(16) <= p_4(16);
  p(15) <= p_4(15);
  p(14) <= p_4(14);
  p(13) <= p_4(13);
  p(12) <= p_4(12);
  p(11) <= p_4(11);
  p(10) <= p_4(10);
  p(9) <= p_4(9);
  p(8) <= p_4(8);
  p(7) <= p_4(7);
  p(6) <= p_4(6);
  p(5) <= p_4(5);
  p(4) <= p_4(4);
  p(3) <= p_4(3);
  p(2) <= p_4(2);
  p(1) <= p_4(1);
  p(0) <= p_4(0);
  VCC_0 : VCC
    port map (
      P => NLW_VCC_P_UNCONNECTED
    );
  GND_1 : GND
    port map (
      G => NLW_GND_G_UNCONNECTED
    );
  BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000 : DSP48E
    generic map(
      AREG => 1,
      ACASCREG => 1,
      BREG => 1,
      BCASCREG => 1,
      B_INPUT => "DIRECT",
      MREG => 1,
      PREG => 1,
      CARRYINREG => 0,
      OPMODEREG => 0,
      ALUMODEREG => 0,
      CARRYINSELREG => 0,
      MULTCARRYINREG => 0,
      USE_MULT => "MULT_S",
      A_INPUT => "DIRECT",
      MASK => X"3FFFFFFFFFFF",
      USE_SIMD => "ONE48",
      USE_PATTERN_DETECT => "NO_PATDET",
      PATTERN => X"000000000000",
      SEL_PATTERN => "PATTERN",
      SEL_MASK => "MASK",
      SEL_ROUNDING_MASK => "SEL_MASK",
      AUTORESET_PATTERN_DETECT => FALSE,
      AUTORESET_PATTERN_DETECT_OPTINV => "MATCH",
      CREG => 0
    )
    port map (
      CARRYIN => BU2_zero_detect(0),
      CEA1 => BU2_zero_detect(0),
      CEA2 => ce,
      CEB1 => BU2_zero_detect(0),
      CEB2 => ce,
      CEC => BU2_zero_detect(0),
      CECTRL => BU2_zero_detect(0),
      CEP => ce,
      CEM => ce,
      CECARRYIN => BU2_zero_detect(0),
      CEMULTCARRYIN => BU2_zero_detect(0),
      CLK => clk,
      RSTA => BU2_zero_detect(0),
      RSTB => BU2_zero_detect(0),
      RSTC => BU2_zero_detect(0),
      RSTCTRL => BU2_zero_detect(0),
      RSTP => BU2_zero_detect(0),
      RSTM => BU2_zero_detect(0),
      RSTALLCARRYIN => BU2_zero_detect(0),
      CEALUMODE => BU2_zero_detect(0),
      RSTALUMODE => BU2_zero_detect(0),
      PATTERNBDETECT => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PATTERNBDETECT_UNCONNECTED,
      PATTERNDETECT => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PATTERNDETECT_UNCONNECTED,
      OVERFLOW => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_OVERFLOW_UNCONNECTED,
      UNDERFLOW => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_UNDERFLOW_UNCONNECTED,
      CARRYCASCIN => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYCASCIN_UNCONNECTED,
      CARRYCASCOUT => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYCASCOUT_UNCONNECTED,
      MULTSIGNIN => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_MULTSIGNIN_UNCONNECTED,
      MULTSIGNOUT => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_MULTSIGNOUT_UNCONNECTED,
      A(29) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_A_29_UNCONNECTED,
      A(28) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_A_28_UNCONNECTED,
      A(27) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_A_27_UNCONNECTED,
      A(26) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_A_26_UNCONNECTED,
      A(25) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_A_25_UNCONNECTED,
      A(24) => BU2_zero_detect(0),
      A(23) => BU2_zero_detect(0),
      A(22) => BU2_zero_detect(0),
      A(21) => BU2_zero_detect(0),
      A(20) => BU2_zero_detect(0),
      A(19) => BU2_zero_detect(0),
      A(18) => BU2_zero_detect(0),
      A(17) => BU2_zero_detect(0),
      A(16) => BU2_zero_detect(0),
      A(15) => a_2(15),
      A(14) => a_2(14),
      A(13) => a_2(13),
      A(12) => a_2(12),
      A(11) => a_2(11),
      A(10) => a_2(10),
      A(9) => a_2(9),
      A(8) => a_2(8),
      A(7) => a_2(7),
      A(6) => a_2(6),
      A(5) => a_2(5),
      A(4) => a_2(4),
      A(3) => a_2(3),
      A(2) => a_2(2),
      A(1) => a_2(1),
      A(0) => a_2(0),
      PCIN(47) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_47_UNCONNECTED,
      PCIN(46) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_46_UNCONNECTED,
      PCIN(45) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_45_UNCONNECTED,
      PCIN(44) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_44_UNCONNECTED,
      PCIN(43) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_43_UNCONNECTED,
      PCIN(42) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_42_UNCONNECTED,
      PCIN(41) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_41_UNCONNECTED,
      PCIN(40) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_40_UNCONNECTED,
      PCIN(39) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_39_UNCONNECTED,
      PCIN(38) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_38_UNCONNECTED,
      PCIN(37) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_37_UNCONNECTED,
      PCIN(36) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_36_UNCONNECTED,
      PCIN(35) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_35_UNCONNECTED,
      PCIN(34) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_34_UNCONNECTED,
      PCIN(33) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_33_UNCONNECTED,
      PCIN(32) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_32_UNCONNECTED,
      PCIN(31) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_31_UNCONNECTED,
      PCIN(30) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_30_UNCONNECTED,
      PCIN(29) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_29_UNCONNECTED,
      PCIN(28) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_28_UNCONNECTED,
      PCIN(27) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_27_UNCONNECTED,
      PCIN(26) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_26_UNCONNECTED,
      PCIN(25) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_25_UNCONNECTED,
      PCIN(24) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_24_UNCONNECTED,
      PCIN(23) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_23_UNCONNECTED,
      PCIN(22) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_22_UNCONNECTED,
      PCIN(21) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_21_UNCONNECTED,
      PCIN(20) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_20_UNCONNECTED,
      PCIN(19) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_19_UNCONNECTED,
      PCIN(18) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_18_UNCONNECTED,
      PCIN(17) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_17_UNCONNECTED,
      PCIN(16) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_16_UNCONNECTED,
      PCIN(15) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_15_UNCONNECTED,
      PCIN(14) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_14_UNCONNECTED,
      PCIN(13) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_13_UNCONNECTED,
      PCIN(12) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_12_UNCONNECTED,
      PCIN(11) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_11_UNCONNECTED,
      PCIN(10) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_10_UNCONNECTED,
      PCIN(9) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_9_UNCONNECTED,
      PCIN(8) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_8_UNCONNECTED,
      PCIN(7) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_7_UNCONNECTED,
      PCIN(6) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_6_UNCONNECTED,
      PCIN(5) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_5_UNCONNECTED,
      PCIN(4) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_4_UNCONNECTED,
      PCIN(3) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_3_UNCONNECTED,
      PCIN(2) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_2_UNCONNECTED,
      PCIN(1) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_1_UNCONNECTED,
      PCIN(0) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCIN_0_UNCONNECTED,
      B(17) => BU2_zero_detect(0),
      B(16) => BU2_zero_detect(0),
      B(15) => b_3(15),
      B(14) => b_3(14),
      B(13) => b_3(13),
      B(12) => b_3(12),
      B(11) => b_3(11),
      B(10) => b_3(10),
      B(9) => b_3(9),
      B(8) => b_3(8),
      B(7) => b_3(7),
      B(6) => b_3(6),
      B(5) => b_3(5),
      B(4) => b_3(4),
      B(3) => b_3(3),
      B(2) => b_3(2),
      B(1) => b_3(1),
      B(0) => b_3(0),
      C(47) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_47_UNCONNECTED,
      C(46) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_46_UNCONNECTED,
      C(45) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_45_UNCONNECTED,
      C(44) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_44_UNCONNECTED,
      C(43) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_43_UNCONNECTED,
      C(42) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_42_UNCONNECTED,
      C(41) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_41_UNCONNECTED,
      C(40) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_40_UNCONNECTED,
      C(39) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_39_UNCONNECTED,
      C(38) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_38_UNCONNECTED,
      C(37) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_37_UNCONNECTED,
      C(36) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_36_UNCONNECTED,
      C(35) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_35_UNCONNECTED,
      C(34) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_34_UNCONNECTED,
      C(33) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_33_UNCONNECTED,
      C(32) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_32_UNCONNECTED,
      C(31) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_31_UNCONNECTED,
      C(30) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_30_UNCONNECTED,
      C(29) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_29_UNCONNECTED,
      C(28) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_28_UNCONNECTED,
      C(27) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_27_UNCONNECTED,
      C(26) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_26_UNCONNECTED,
      C(25) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_25_UNCONNECTED,
      C(24) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_24_UNCONNECTED,
      C(23) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_23_UNCONNECTED,
      C(22) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_22_UNCONNECTED,
      C(21) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_21_UNCONNECTED,
      C(20) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_20_UNCONNECTED,
      C(19) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_19_UNCONNECTED,
      C(18) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_18_UNCONNECTED,
      C(17) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_17_UNCONNECTED,
      C(16) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_16_UNCONNECTED,
      C(15) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_15_UNCONNECTED,
      C(14) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_14_UNCONNECTED,
      C(13) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_13_UNCONNECTED,
      C(12) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_12_UNCONNECTED,
      C(11) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_11_UNCONNECTED,
      C(10) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_10_UNCONNECTED,
      C(9) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_9_UNCONNECTED,
      C(8) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_8_UNCONNECTED,
      C(7) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_7_UNCONNECTED,
      C(6) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_6_UNCONNECTED,
      C(5) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_5_UNCONNECTED,
      C(4) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_4_UNCONNECTED,
      C(3) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_3_UNCONNECTED,
      C(2) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_2_UNCONNECTED,
      C(1) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_1_UNCONNECTED,
      C(0) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_C_0_UNCONNECTED,
      CARRYINSEL(2) => BU2_zero_detect(0),
      CARRYINSEL(1) => BU2_zero_detect(0),
      CARRYINSEL(0) => BU2_zero_detect(0),
      OPMODE(6) => BU2_zero_detect(0),
      OPMODE(5) => BU2_zero_detect(0),
      OPMODE(4) => BU2_zero_detect(0),
      OPMODE(3) => BU2_zero_detect(0),
      OPMODE(2) => BU2_N1,
      OPMODE(1) => BU2_zero_detect(0),
      OPMODE(0) => BU2_N1,
      BCIN(17) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_17_UNCONNECTED,
      BCIN(16) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_16_UNCONNECTED,
      BCIN(15) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_15_UNCONNECTED,
      BCIN(14) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_14_UNCONNECTED,
      BCIN(13) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_13_UNCONNECTED,
      BCIN(12) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_12_UNCONNECTED,
      BCIN(11) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_11_UNCONNECTED,
      BCIN(10) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_10_UNCONNECTED,
      BCIN(9) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_9_UNCONNECTED,
      BCIN(8) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_8_UNCONNECTED,
      BCIN(7) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_7_UNCONNECTED,
      BCIN(6) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_6_UNCONNECTED,
      BCIN(5) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_5_UNCONNECTED,
      BCIN(4) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_4_UNCONNECTED,
      BCIN(3) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_3_UNCONNECTED,
      BCIN(2) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_2_UNCONNECTED,
      BCIN(1) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_1_UNCONNECTED,
      BCIN(0) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCIN_0_UNCONNECTED,
      ALUMODE(3) => BU2_zero_detect(0),
      ALUMODE(2) => BU2_zero_detect(0),
      ALUMODE(1) => BU2_zero_detect(0),
      ALUMODE(0) => BU2_zero_detect(0),
      PCOUT(47) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_47_UNCONNECTED,
      PCOUT(46) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_46_UNCONNECTED,
      PCOUT(45) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_45_UNCONNECTED,
      PCOUT(44) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_44_UNCONNECTED,
      PCOUT(43) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_43_UNCONNECTED,
      PCOUT(42) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_42_UNCONNECTED,
      PCOUT(41) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_41_UNCONNECTED,
      PCOUT(40) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_40_UNCONNECTED,
      PCOUT(39) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_39_UNCONNECTED,
      PCOUT(38) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_38_UNCONNECTED,
      PCOUT(37) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_37_UNCONNECTED,
      PCOUT(36) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_36_UNCONNECTED,
      PCOUT(35) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_35_UNCONNECTED,
      PCOUT(34) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_34_UNCONNECTED,
      PCOUT(33) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_33_UNCONNECTED,
      PCOUT(32) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_32_UNCONNECTED,
      PCOUT(31) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_31_UNCONNECTED,
      PCOUT(30) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_30_UNCONNECTED,
      PCOUT(29) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_29_UNCONNECTED,
      PCOUT(28) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_28_UNCONNECTED,
      PCOUT(27) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_27_UNCONNECTED,
      PCOUT(26) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_26_UNCONNECTED,
      PCOUT(25) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_25_UNCONNECTED,
      PCOUT(24) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_24_UNCONNECTED,
      PCOUT(23) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_23_UNCONNECTED,
      PCOUT(22) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_22_UNCONNECTED,
      PCOUT(21) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_21_UNCONNECTED,
      PCOUT(20) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_20_UNCONNECTED,
      PCOUT(19) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_19_UNCONNECTED,
      PCOUT(18) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_18_UNCONNECTED,
      PCOUT(17) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_17_UNCONNECTED,
      PCOUT(16) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_16_UNCONNECTED,
      PCOUT(15) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_15_UNCONNECTED,
      PCOUT(14) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_14_UNCONNECTED,
      PCOUT(13) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_13_UNCONNECTED,
      PCOUT(12) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_12_UNCONNECTED,
      PCOUT(11) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_11_UNCONNECTED,
      PCOUT(10) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_10_UNCONNECTED,
      PCOUT(9) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_9_UNCONNECTED,
      PCOUT(8) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_8_UNCONNECTED,
      PCOUT(7) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_7_UNCONNECTED,
      PCOUT(6) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_6_UNCONNECTED,
      PCOUT(5) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_5_UNCONNECTED,
      PCOUT(4) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_4_UNCONNECTED,
      PCOUT(3) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_3_UNCONNECTED,
      PCOUT(2) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_2_UNCONNECTED,
      PCOUT(1) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_1_UNCONNECTED,
      PCOUT(0) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_PCOUT_0_UNCONNECTED,
      P(47) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_47_UNCONNECTED,
      P(46) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_46_UNCONNECTED,
      P(45) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_45_UNCONNECTED,
      P(44) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_44_UNCONNECTED,
      P(43) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_43_UNCONNECTED,
      P(42) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_42_UNCONNECTED,
      P(41) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_41_UNCONNECTED,
      P(40) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_40_UNCONNECTED,
      P(39) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_39_UNCONNECTED,
      P(38) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_38_UNCONNECTED,
      P(37) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_37_UNCONNECTED,
      P(36) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_36_UNCONNECTED,
      P(35) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_35_UNCONNECTED,
      P(34) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_34_UNCONNECTED,
      P(33) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_33_UNCONNECTED,
      P(32) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_P_32_UNCONNECTED,
      P(31) => p_4(31),
      P(30) => p_4(30),
      P(29) => p_4(29),
      P(28) => p_4(28),
      P(27) => p_4(27),
      P(26) => p_4(26),
      P(25) => p_4(25),
      P(24) => p_4(24),
      P(23) => p_4(23),
      P(22) => p_4(22),
      P(21) => p_4(21),
      P(20) => p_4(20),
      P(19) => p_4(19),
      P(18) => p_4(18),
      P(17) => p_4(17),
      P(16) => p_4(16),
      P(15) => p_4(15),
      P(14) => p_4(14),
      P(13) => p_4(13),
      P(12) => p_4(12),
      P(11) => p_4(11),
      P(10) => p_4(10),
      P(9) => p_4(9),
      P(8) => p_4(8),
      P(7) => p_4(7),
      P(6) => p_4(6),
      P(5) => p_4(5),
      P(4) => p_4(4),
      P(3) => p_4(3),
      P(2) => p_4(2),
      P(1) => p_4(1),
      P(0) => p_4(0),
      BCOUT(17) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_17_UNCONNECTED,
      BCOUT(16) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_16_UNCONNECTED,
      BCOUT(15) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_15_UNCONNECTED,
      BCOUT(14) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_14_UNCONNECTED,
      BCOUT(13) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_13_UNCONNECTED,
      BCOUT(12) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_12_UNCONNECTED,
      BCOUT(11) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_11_UNCONNECTED,
      BCOUT(10) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_10_UNCONNECTED,
      BCOUT(9) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_9_UNCONNECTED,
      BCOUT(8) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_8_UNCONNECTED,
      BCOUT(7) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_7_UNCONNECTED,
      BCOUT(6) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_6_UNCONNECTED,
      BCOUT(5) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_5_UNCONNECTED,
      BCOUT(4) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_4_UNCONNECTED,
      BCOUT(3) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_3_UNCONNECTED,
      BCOUT(2) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_2_UNCONNECTED,
      BCOUT(1) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_1_UNCONNECTED,
      BCOUT(0) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_BCOUT_0_UNCONNECTED,
      ACIN(29) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_29_UNCONNECTED,
      ACIN(28) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_28_UNCONNECTED,
      ACIN(27) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_27_UNCONNECTED,
      ACIN(26) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_26_UNCONNECTED,
      ACIN(25) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_25_UNCONNECTED,
      ACIN(24) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_24_UNCONNECTED,
      ACIN(23) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_23_UNCONNECTED,
      ACIN(22) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_22_UNCONNECTED,
      ACIN(21) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_21_UNCONNECTED,
      ACIN(20) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_20_UNCONNECTED,
      ACIN(19) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_19_UNCONNECTED,
      ACIN(18) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_18_UNCONNECTED,
      ACIN(17) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_17_UNCONNECTED,
      ACIN(16) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_16_UNCONNECTED,
      ACIN(15) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_15_UNCONNECTED,
      ACIN(14) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_14_UNCONNECTED,
      ACIN(13) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_13_UNCONNECTED,
      ACIN(12) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_12_UNCONNECTED,
      ACIN(11) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_11_UNCONNECTED,
      ACIN(10) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_10_UNCONNECTED,
      ACIN(9) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_9_UNCONNECTED,
      ACIN(8) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_8_UNCONNECTED,
      ACIN(7) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_7_UNCONNECTED,
      ACIN(6) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_6_UNCONNECTED,
      ACIN(5) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_5_UNCONNECTED,
      ACIN(4) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_4_UNCONNECTED,
      ACIN(3) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_3_UNCONNECTED,
      ACIN(2) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_2_UNCONNECTED,
      ACIN(1) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_1_UNCONNECTED,
      ACIN(0) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACIN_0_UNCONNECTED,
      ACOUT(29) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_29_UNCONNECTED,
      ACOUT(28) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_28_UNCONNECTED,
      ACOUT(27) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_27_UNCONNECTED,
      ACOUT(26) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_26_UNCONNECTED,
      ACOUT(25) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_25_UNCONNECTED,
      ACOUT(24) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_24_UNCONNECTED,
      ACOUT(23) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_23_UNCONNECTED,
      ACOUT(22) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_22_UNCONNECTED,
      ACOUT(21) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_21_UNCONNECTED,
      ACOUT(20) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_20_UNCONNECTED,
      ACOUT(19) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_19_UNCONNECTED,
      ACOUT(18) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_18_UNCONNECTED,
      ACOUT(17) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_17_UNCONNECTED,
      ACOUT(16) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_16_UNCONNECTED,
      ACOUT(15) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_15_UNCONNECTED,
      ACOUT(14) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_14_UNCONNECTED,
      ACOUT(13) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_13_UNCONNECTED,
      ACOUT(12) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_12_UNCONNECTED,
      ACOUT(11) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_11_UNCONNECTED,
      ACOUT(10) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_10_UNCONNECTED,
      ACOUT(9) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_9_UNCONNECTED,
      ACOUT(8) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_8_UNCONNECTED,
      ACOUT(7) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_7_UNCONNECTED,
      ACOUT(6) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_6_UNCONNECTED,
      ACOUT(5) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_5_UNCONNECTED,
      ACOUT(4) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_4_UNCONNECTED,
      ACOUT(3) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_3_UNCONNECTED,
      ACOUT(2) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_2_UNCONNECTED,
      ACOUT(1) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_1_UNCONNECTED,
      ACOUT(0) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_ACOUT_0_UNCONNECTED,
      CARRYOUT(3) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYOUT_3_UNCONNECTED,
      CARRYOUT(2) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYOUT_2_UNCONNECTED,
      CARRYOUT(1) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYOUT_1_UNCONNECTED,
      CARRYOUT(0) => NLW_BU2_U0_gEMBEDDED_MULT_gEMB_MULTS_only_gDSP_iDSP_Mmult_mult0000_CARRYOUT_0_UNCONNECTED
    );
  BU2_XST_VCC : VCC
    port map (
      P => BU2_N1
    );
  BU2_XST_GND : GND
    port map (
      G => BU2_zero_detect(0)
    );

end STRUCTURE;

-- synthesis translate_on
